# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
fos_ck_editor:
    configs:
        main_config:
            toolbar:
                - { name: "styles", items: [ 'Bold', 'Italic', 'Underline', 'Strike', 'Link',
                                             'RemoveFormat','Subscript','Superscript', 'NewPage',
                                             'DocProps','Print','document', 'Outdent', 'Indent',
                                             'JustifyLeft', 'JustifyCenter', 'JustifyRight',
                                             'Cut','Undo','Redo','Find','Replace','SelectAll',
                                             'Scayt','TextColor', 'BGColor' ,'Blockquote',
                                             'BidiLtr', 'BidiRtl','Link','Unlink','CreatePlaceholder','Image',
                                             'HorizontalRule','Smiley', 'SpecialChar', 'Maximize',
                                             'Styles','Font','FontSize','About' ] }