<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWTGd6EM\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWTGd6EM/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWTGd6EM.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWTGd6EM\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerWTGd6EM\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'WTGd6EM',
    'container.build_id' => '15ebadfb',
    'container.build_time' => 1616669697,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWTGd6EM');
